apiVersion: v2
name: node-local-cache
description: CSI driver for node-local ephemeral cache volumes
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - csi
  - storage
  - cache
  - kubernetes
home: https://github.com/Kapernikov/kube-ephemeral-per-node-cache-csi
sources:
  - https://github.com/Kapernikov/kube-ephemeral-per-node-cache-csi
maintainers:
  - name: Kapernikov
